name: 🔑 Request Unity Activation File (.alf)

on:
  workflow_dispatch:

jobs:
  activation:
    name: 📄 Generate Unity Activation File (.alf)
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🔑 Request Activation File
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 6000.3.22f1

      - name: 📤 Upload Activation File Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Unity_v6000.3.22f1.alf
          path: '**/*.alf'
          retention-days: 1
